# Generated by Django 5.2 on 2026-06-22 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_seed_default_exercises'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='is_bodyweight',
        ),
        migrations.AddField(
            model_name='exercise',
            name='tracking',
            field=models.CharField(choices=[('weight_reps', 'Вес и повторения'), ('bodyweight', 'Свой вес (вес опционально)'), ('duration', 'Время'), ('distance', 'Дистанция и время')], default='weight_reps', max_length=16),
        ),
        migrations.AddField(
            model_name='workoutset',
            name='distance_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='workoutset',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workoutset',
            name='duration_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='primary_muscle',
            field=models.CharField(choices=[('chest', 'Грудь'), ('lats', 'Широчайшие'), ('traps', 'Трапеции'), ('lower_back', 'Поясница'), ('biceps', 'Бицепс'), ('triceps', 'Трицепс'), ('forearms', 'Предплечья'), ('shoulders', 'Плечи'), ('quads', 'Квадрицепс'), ('hamstrings', 'Бицепс бедра'), ('glutes', 'Ягодицы'), ('calves', 'Икры'), ('abs', 'Пресс'), ('obliques', 'Косые'), ('cardio', 'Кардио')], max_length=16),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='region',
            field=models.CharField(choices=[('chest', 'Грудь'), ('back', 'Спина'), ('arms', 'Руки'), ('legs', 'Ноги'), ('core', 'Пресс'), ('cardio', 'Кардио')], max_length=16),
        ),
        migrations.AlterField(
            model_name='workoutset',
            name='reps',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
